server:
  port: 9411
spring:
  application:
    name: sleuth-server
  sleuth:
    enabled: false #表示当前程序不使用sleuth
    sampler:
        # 表示以100%的概率将链路的数据上传给zipkin server ，默认为0.1
      percentage: 1.0

zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: 192.168.55.2:9200