
server:
  port: 8081

spring:
  application:
    name: user-provider
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/spring-cloud-test?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: src/main/java/**/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.fsdm.pojo  # 注意：对应实体类的路径
  config-location: classpath:mybatis/mybatis.xml
