feign:
  hystrix:
    # 
    enabled: true

server:
  port: 8082

spring:
  application:
    name: user-cusumer
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /**

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
